### ISSUE TITLE
Issues running bin/setup with Ruby 2.4.0

### ISSUE THREAD

**Issue by cknadler** [nielsenramon/chalk#38]
Looks like there are some issues running `bin/setup` with newer versions of ruby, specifically `2.4.0`. I get the following errors when executing `bundle install`.

```
Resolving dependencies...
Using i18n 0.7.0
Installing json 1.8.3 with native extensions
Using minitest 5.10.1
Using thread_safe 0.3.5
Using public_suffix 2.0.4
Using colorator 1.1.0
Using colored 1.2
Using concurrent-ruby 1.0.4
Using ffi 1.9.14
Using execjs 2.7.0
Using forwardable-extended 2.6.0
Using mercenary 0.3.6
Using mini_portile2 2.1.0
Using parallel 1.10.0
Using yell 2.0.7
Using sass 3.4.23
Using rb-fsevent 0.9.8
Using kramdown 1.13.1
Using liquid 3.0.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using rack 1.6.5
Using jekyll-paginate 1.1.0
Using mini_magick 4.6.0
Using bundler 1.13.7
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/usr/local/opt/ruby/bin/ruby -r ./siteconf20170112-63763-1tzov3x.rb extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c:861:25: error: use of undeclared identifier 'rb_cFixnum'
    } else if (klass == rb_cFixnum) {
                        ^
generator.c:863:25: error: use of undeclared identifier 'rb_cBignum'
    } else if (klass == rb_cBignum) {

[...truncated for brevity...]

6 warnings and 2 errors generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3 for inspection.
Results logged to
/usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-15/2.4.0/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

It seems that json 1.8.3 isn't compatible with ruby 2.4.0. Some information in the following issue.

https://github.com/flori/json/issues/253

There are some workarounds, but it would be great to determine which gem has the hard requirement on json 1.8.3 and see if it can be updated to a newer version of that gem. As far as I can tell, more recent versions (I tested 2.0.0+) work fine with ruby 2.4.0.

**Comment by cknadler** [comment]
Ok, figured out a solution. Adding the following to the top of your project Gemfile solves the incompatibility for now.

```
gem 'json', github: 'flori/json', branch: 'v1.8'
```

I'll make up a pull request with that change. Leaving this open as the above fix is a hack and may not work long term. Would be great to figure out where the dependency is coming from and see if it can be updated or find an alternative.
